import {
  siAkamai,
  siAlgolia,
  siAlpinedotjs,
  siAngular,
  siApache,
  siApollographql,
  siAstro,
  siBootstrap,
  siCaddy,
  siChartdotjs,
  siCloudflare,
  siContentful,
  siD3,
  siDatadog,
  siDocusaurus,
  siDotnet,
  siDrupal,
  siEmberdotjs,
  siEnvoyproxy,
  siExpress,
  siFastly,
  siFathom,
  siFirebase,
  siFlydotio,
  siGatsby,
  siGhost,
  siGithub,
  siGoogleads,
  siGoogleanalytics,
  siGooglecloud,
  siGooglefonts,
  siGoogletagmanager,
  siGsap,
  siHotjar,
  siHotwire,
  siHtmx,
  siHubspot,
  siHugo,
  siIntercom,
  siJekyll,
  siJquery,
  siLeaflet,
  siLit,
  siMapbox,
  siMeta,
  siMixpanel,
  siNetlify,
  siNewrelic,
  siNextdotjs,
  siNginx,
  siNuxt,
  siPhp,
  siPlausibleanalytics,
  siPosthog,
  siReact,
  siReactquery,
  siReactrouter,
  siRemix,
  siRender,
  siRubyonrails,
  siSentry,
  siShopify,
  siSolid,
  siSquarespace,
  siStripe,
  siSvelte,
  siSwiper,
  siThreedotjs,
  siTiktok,
  siTypescript,
  siVercel,
  siVimeo,
  siVuedotjs,
  siWebflow,
  siWistia,
  siWix,
  siWordpress,
  siYoutube,
  siZendesk,
  siZod,
  type SimpleIcon,
} from "simple-icons";

// Simple Icons (CC0) marks for detected technology names. Brands that Simple
// Icons does not carry render without a mark.
export const TECHNOLOGY_ICONS: Readonly<Record<string, SimpleIcon>> = {
  "Next.js": siNextdotjs,
  Nuxt: siNuxt,
  Gatsby: siGatsby,
  Remix: siRemix,
  "React Router": siReactrouter,
  SvelteKit: siSvelte,
  Astro: siAstro,
  Angular: siAngular,
  Vue: siVuedotjs,
  React: siReact,
  "Ruby on Rails": siRubyonrails,
  Express: siExpress,
  PHP: siPhp,
  "ASP.NET": siDotnet,
  WordPress: siWordpress,
  Drupal: siDrupal,
  Ghost: siGhost,
  Shopify: siShopify,
  Webflow: siWebflow,
  Wix: siWix,
  Squarespace: siSquarespace,
  Hugo: siHugo,
  Jekyll: siJekyll,
  Docusaurus: siDocusaurus,
  Vercel: siVercel,
  "Vercel Web Analytics": siVercel,
  "Vercel Speed Insights": siVercel,
  "Vercel Blob": siVercel,
  Netlify: siNetlify,
  GitHub: siGithub,
  "Fly.io": siFlydotio,
  Render: siRender,
  "Google Cloud": siGooglecloud,
  Cloudflare: siCloudflare,
  "Cloudflare Web Analytics": siCloudflare,
  "Cloudflare Turnstile": siCloudflare,
  Fastly: siFastly,
  Akamai: siAkamai,
  nginx: siNginx,
  "Apache HTTP Server": siApache,
  Caddy: siCaddy,
  Envoy: siEnvoyproxy,
  "Google Tag Manager": siGoogletagmanager,
  "Google Analytics": siGoogleanalytics,
  "Google Ads": siGoogleads,
  "Google Fonts": siGooglefonts,
  Plausible: siPlausibleanalytics,
  Fathom: siFathom,
  Hotjar: siHotjar,
  Sentry: siSentry,
  "Datadog RUM": siDatadog,
  "New Relic": siNewrelic,
  jQuery: siJquery,
  Bootstrap: siBootstrap,
  Stripe: siStripe,
  Intercom: siIntercom,
  Svelte: siSvelte,
  SolidJS: siSolid,
  Lit: siLit,
  "Alpine.js": siAlpinedotjs,
  htmx: siHtmx,
  "Ember.js": siEmberdotjs,
  "Hotwire Turbo": siHotwire,
  PostHog: siPosthog,
  Mixpanel: siMixpanel,
  "React Query": siReactquery,
  Zod: siZod,
  "Three.js": siThreedotjs,
  GSAP: siGsap,
  "Apollo Client": siApollographql,
  D3: siD3,
  "Chart.js": siChartdotjs,
  Leaflet: siLeaflet,
  Firebase: siFirebase,
  Swiper: siSwiper,
  Contentful: siContentful,
  "Meta Pixel": siMeta,
  "TikTok Pixel": siTiktok,
  HubSpot: siHubspot,
  Zendesk: siZendesk,
  Wistia: siWistia,
  YouTube: siYoutube,
  Vimeo: siVimeo,
  Algolia: siAlgolia,
  Mapbox: siMapbox,
  TypeScript: siTypescript,
};
